/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import com.raven.popup.AkunPopup;
import java.sql.*;
import java.text.SimpleDateFormat;
import config.DatabaseConfig;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import raven.glasspanepopup.GlassPanePopup;
import com.raven.event.DataChangeListener;
import com.raven.popup.HapusDataPopup;
import com.raven.popup.MemberPopup;
import java.awt.Color;

/**
 *
 * @author Fazaa
 */
public class Form_Akun extends javax.swing.JPanel {

    Connection con = null;
    DefaultTableModel tableModel;
    private DataChangeListener dataChangeListener;
    AkunPopup popup = new AkunPopup();
    MemberPopup popupMember = new MemberPopup();
    HapusDataPopup hapusPopup = new HapusDataPopup();
    int indexTable = 0; // 0 = Akun, 1 = Member

    public Form_Akun() {
        initComponents();
        setOpaque(false);
        getCon();
        setModel();
        popup.setAkunListener(new DataChangeListener() {
            @Override
            public void onDataChanged() {
                loadData();
            }
        });
    }

    private void setModel() {
        String[][] judul = {{"UID", "Nama", "Username", "Password", "Role"}, {"Kode Member","UID", "Nama", "No Telp", "Point", "tanggal Bergabung"}};
        tableModel = new DefaultTableModel(judul[indexTable], 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblAkun.setModel(tableModel);
        loadData();
    }

    private void loadData() {
        if (con != null) {
            try {
                String query = indexTable == 0 ? "SELECT * FROM user ORDER BY level DESC" : "SELECT * FROM member";
                PreparedStatement ps = con.prepareStatement(query);
                ResultSet rs = ps.executeQuery();
                tableModel.setRowCount(0);
                while (rs.next()) {
                    if (indexTable == 0) {
                        String role = null;
                        if (rs.getInt(6) == 1) {
                            role = "Admin";
                        } else {
                            role = "Karyawan";
                        }
                        String[] data = {rs.getString("uid"), rs.getString(3), rs.getString(4), rs.getString(5), role};
                        tableModel.addRow(data);
                    } else {
                        String rawDate = rs.getString(6);
                        String formattedDate = new SimpleDateFormat("yyyy-MM-dd").format(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").parse(rawDate));

                        String[] data = {rs.getString("kode_member"), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), formattedDate};
                        tableModel.addRow(data);
                    }
                }
                rs.close();
                ps.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private void getCon() {
        try {
            con = DatabaseConfig.getConnection();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadAkunKaryawan() {
        if (con != null) {
            try {
                String query = "SELECT * FROM user ORDER BY level DESC";
                PreparedStatement ps = con.prepareStatement(query);
                ResultSet rs = ps.executeQuery();
                tableModel.setRowCount(0);
                while (rs.next()) {
                    String role = null;
                    if (rs.getInt(6) == 1) {
                        role = "Admin";
                    } else {
                        role = "Karyawan";
                    }
                    String[] data = {rs.getString("uid"), rs.getString(3), rs.getString(4), rs.getString(5), role};
                    tableModel.addRow(data);
                }
                rs.close();
                ps.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judul = new javax.swing.JLabel();
        panelRound1 = new com.raven.swing.PanelRound();
        button1 = new com.raven.util.Button();
        button2 = new com.raven.util.Button();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAkun = new com.raven.swing.TableColumn();
        btnUpdate = new com.raven.util.Button();
        btnDelete = new com.raven.util.Button();
        btnAdd = new com.raven.util.Button();

        judul.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        judul.setForeground(new java.awt.Color(33, 53, 85));
        judul.setText("AKUN");
        judul.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        judul.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 1, 1));
        judul.setFocusable(false);

        panelRound1.setBackground(new java.awt.Color(33, 53, 85));

        button1.setForeground(new java.awt.Color(0, 0, 0));
        button1.setText("DAFTAR AKUN");
        button1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setBackground(new java.awt.Color(144, 154, 170));
        button2.setForeground(new java.awt.Color(33, 53, 85));
        button2.setText("DAFTAR MEMBER");
        button2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        jScrollPane2.setBorder(null);

        tblAkun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KODE", "NAMA MENU", "HARGA", "QTY", "SUBTOTAL", "AKSI"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAkun.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblAkun);

        btnUpdate.setBackground(new java.awt.Color(255, 157, 35));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("UPDATE");
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(208, 90, 90));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("DELETE");
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(97, 131, 175));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("ADD");
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                        .addGap(15, 15, 15)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(485, 485, 485))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(judul)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(judul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        indexTable = 0;
        button1.setBackground(new Color(255, 255, 255));
        button2.setBackground(new Color(144, 154, 170));
        setModel();
    }//GEN-LAST:event_button1ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblAkun.getSelectedRow();
        if (selectedRow != -1) {
            if (indexTable == 0) {
                int role = -1;
                String getRole = tblAkun.getValueAt(selectedRow, 4).toString();
                if (getRole == "Admin") {
                    role = 1;
                } else {
                    role = 0;
                }
                String uid = tblAkun.getValueAt(selectedRow, 0).toString();
                String nama = tblAkun.getValueAt(selectedRow, 1).toString();
                String username = tblAkun.getValueAt(selectedRow, 2).toString();
                String password = tblAkun.getValueAt(selectedRow, 3).toString();

                popup.setEditMode(uid, nama, username, password, role);
                GlassPanePopup.showPopup(popup);
            } else {
                String kode_member = tblAkun.getValueAt(selectedRow, 0).toString();
                String uid = tblAkun.getValueAt(selectedRow, 1).toString();
                String nama = tblAkun.getValueAt(selectedRow, 2).toString();
                String noTelp = tblAkun.getValueAt(selectedRow, 3).toString();

                popupMember.setEditMode(kode_member, uid, nama, noTelp);
                GlassPanePopup.showPopup(popupMember);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Silakan pilih data yang ingin diedit!");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = tblAkun.getSelectedRow();
        if (selectedRow != -1) {
            if (indexTable == 0) {
                String uid = tblAkun.getValueAt(selectedRow, 0).toString();
                hapusPopup.setData("user", "uid", uid);
                hapusPopup.setDataChangeListener(() -> loadAkunKaryawan());
                GlassPanePopup.showPopup(hapusPopup);
            } else {
                String kodeMember = tblAkun.getValueAt(selectedRow, 0).toString();
                hapusPopup.setData("member", "kode_member", kodeMember);
                hapusPopup.setDataChangeListener(() -> loadData());
                GlassPanePopup.showPopup(hapusPopup);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Silakan pilih data yang ingin dihapus!");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if (indexTable == 0) {
            GlassPanePopup.showPopup(new AkunPopup());
        } else {
            GlassPanePopup.showPopup(new MemberPopup());
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        indexTable = 1;
        button2.setBackground(new Color(255, 255, 255));
        button1.setBackground(new Color(144, 154, 170));
        setModel();
    }//GEN-LAST:event_button2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.util.Button btnAdd;
    private com.raven.util.Button btnDelete;
    private com.raven.util.Button btnUpdate;
    private com.raven.util.Button button1;
    private com.raven.util.Button button2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel judul;
    private com.raven.swing.PanelRound panelRound1;
    private com.raven.swing.TableColumn tblAkun;
    // End of variables declaration//GEN-END:variables
}
