/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import config.DatabaseConfig;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MI TA
 */
public class Form_AbsenAdmin extends javax.swing.JPanel {

    /**
     * Creates new form Form_AbsenAdmin
     */
    Connection con = null;
    DefaultTableModel tableModel;

    public Form_AbsenAdmin() {
        initComponents();
        getCon();
        setModel();
    }

    private void setModel() {
        String[] judul = {"Nama", "Tanggal", "Masuk", "Keluar", "Keterangan"};
        tableModel = new DefaultTableModel(judul, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblAbsen.setModel(tableModel);
        loadData();
    }

    private void loadData() {
        if (con != null) {
            try {
                String q = "SELECT u.nama, a.tanggal, a.waktu_masuk, a.waktu_keluar, a.keterangan FROM Absensi a JOIN user u ON a.id_user = u.id_user";
                PreparedStatement ps = con.prepareStatement(q);
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    String[] data = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)};
                    tableModel.addRow(data);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private void getCon() {
        try {
            con = DatabaseConfig.getConnection();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAbsen = new com.raven.swing.TableColumn();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 150, 30));

        jScrollPane2.setBorder(null);

        tblAbsen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAMA", "TANGGAL", "MASUK", "KELUAR", "STATUS KEHADIRAN", "KET"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAbsen.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblAbsen);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 770, 330));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.raven.swing.TableColumn tblAbsen;
    // End of variables declaration//GEN-END:variables
}
