/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import config.DatabaseConfig;
import config.Session;
import java.awt.BorderLayout;
import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fazaa
 */
public class Form_Absensi extends javax.swing.JPanel {

       Connection con = null;
    DefaultTableModel tableModel;
    private Component currentForm = null;

    public Form_Absensi() {
        initComponents();
        setOpaque(false);
        getCon();
        initializeFormBasedOnRole();
    }

    private void getCon() {
        try {
            con = DatabaseConfig.getConnection();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, 
                "Gagal menghubungkan ke database: " + e.getMessage(), 
                "Error Database", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Inisialisasi form berdasarkan role pengguna
     */
    private void initializeFormBasedOnRole() {
        try {
            String userRole = Session.getRole();
            
            // Validasi role tidak null atau kosong
            if (userRole == null || userRole.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                    "Role pengguna tidak ditemukan. Silakan login kembali.", 
                    "Error Session", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // Load form berdasarkan role
            if (userRole.equalsIgnoreCase("Admin")) {
                showForm(new Form_AbsenAdmin());
                System.out.println("Loading Form Admin untuk role: " + userRole);
            } else {
                showForm(new Form_AbsenKaryawan());
                System.out.println("Loading Form Karyawan untuk role: " + userRole);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, 
                "Terjadi kesalahan saat memuat form: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            
            // Fallback ke form karyawan jika terjadi error
            try {
                showForm(new Form_AbsenKaryawan());
            } catch (Exception fallbackError) {
                System.err.println("Gagal memuat form fallback: " + fallbackError.getMessage());
            }
        }
    }
    
    /**
     * Menampilkan form/komponen di dalam body panel
     * @param com Komponen yang akan ditampilkan
     */
    public void showForm(Component com) {
        if (com == null) {
            System.err.println("Warning: Komponen yang akan ditampilkan adalah null");
            return;
        }
        
        try {
            // Hapus komponen sebelumnya
            body.removeAll();
            
            // Set layout yang tepat untuk body
            body.setLayout(new BorderLayout());
            
            // Tambahkan komponen baru
            body.add(com, BorderLayout.CENTER);
            
            // Simpan referensi form saat ini
            currentForm = com;
            
            // Refresh tampilan
            body.revalidate();
            body.repaint();
            
            // Update parent container juga
            this.revalidate();
            this.repaint();
            
            System.out.println("Form berhasil dimuat: " + com.getClass().getSimpleName());
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, 
                "Gagal menampilkan form: " + e.getMessage(), 
                "Error Display", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Mendapatkan form yang sedang aktif
     * @return Komponen form yang sedang ditampilkan
     */
    public Component getCurrentForm() {
        return currentForm;
    }
    
    /**
     * Refresh form berdasarkan role saat ini
     */
    public void refreshForm() {
        initializeFormBasedOnRole();
    }
    
    /**
     * Cleanup resources saat panel ditutup
     */
    public void cleanup() {
        try {
            if (con != null && !con.isClosed()) {
                con.close();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judul = new javax.swing.JLabel();
        panelRound1 = new com.raven.swing.PanelRound();
        body = new javax.swing.JPanel();

        judul.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        judul.setForeground(new java.awt.Color(33, 53, 85));
        judul.setText("PRESENSI");
        judul.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        judul.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 1, 1));
        judul.setFocusable(false);

        panelRound1.setBackground(new java.awt.Color(33, 53, 85));
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setOpaque(false);
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelRound1.add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 770, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(judul)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(judul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JLabel judul;
    private com.raven.swing.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables
}
