/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

/**
 *
 * @author Fazaa
 */

import config.DatabaseConfig;
import java.sql.*;
import javax.swing.JOptionPane;

public class test extends javax.swing.JPanel {

    /**
     * Creates new form test
     */
    Connection con = null;
    public test() {
        initComponents();
        try {
            con = DatabaseConfig.getConnection();
        } catch (Exception e) {
        }
    }

     private String RFIDId = "";
    private long lastTime = 0;
    private final long RFID_THRESHOLD = 100;                            

    private void tampilRFID() {
        try {
            String query = "SELECT * FROM member WHERE uid = ? LIMIT 1";
            String rfid = RFIDId;
            try (PreparedStatement ps = con.prepareStatement(query)) {

                ps.setString(1, rfid);

                ResultSet hasil = ps.executeQuery();
                if (hasil.next()) {
                    member.setText(hasil.getString("nama_member") + " | " + hasil.getInt("point")); 
                } else {
                    JOptionPane.showMessageDialog(this, "RFID Tidak terdaftar!", "Error", JOptionPane.ERROR_MESSAGE);
                    member.setText("");
                }
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        member = new com.raven.util.TextField();

        member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberActionPerformed(evt);
            }
        });
        member.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                memberKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(member, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(member, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memberActionPerformed

    private void memberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_memberKeyTyped
        long currentTime = System.currentTimeMillis();
        char c = evt.getKeyChar();

        // Reset RFIDId kalau inputnya lambat
        if (lastTime != 0 && (currentTime - lastTime) > RFID_THRESHOLD) {
            RFIDId = "";
        }

        RFIDId += c;
        lastTime = currentTime;

        if (c == '\n' || c == '\r') {
            RFIDId = RFIDId.replace("\n", "");
            RFIDId = RFIDId.replace("\r", "");
            if (RFIDId.length() >= 9) {
                System.out.println("Scan RFID Terdeteksi: " + RFIDId);
                tampilRFID();
            } else {
                System.out.println("RFID tidak valid, panjang kurang dari 9 karakter.");
            }
            // Kosongkan RFIDId setelah pemrosesan
            RFIDId = "";
//            userInput.setText("");
        }
    }//GEN-LAST:event_memberKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.util.TextField member;
    // End of variables declaration//GEN-END:variables
}
