/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.raven.Login;

import com.raven.main.Main;
import java.sql.*;
import config.DatabaseConfig;
import config.Session;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author MI TA
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    Connection con = null;
    URL[] iconURL;

    public Login() {
        initComponents();
        getCon();
        iconURL = new URL[2]; // 0 = eye, 1 = cross
        iconURL[0] = getClass().getResource("/com/raven/icon/eye.png");
        iconURL[1] = getClass().getResource("/com/raven/icon/crossed-eye.png");
    }

    private void getCon() {
        try {
            con = DatabaseConfig.getConnection();
        } catch (Exception e) {
        }
    }

    public void loginAction() {
        try {
            String query = "SELECT * FROM user WHERE username = ? AND password = ? LIMIT 1";
            String usn = userInput.getText();
            String pass = passInput.getText();
            try (PreparedStatement ps = con.prepareStatement(query)) {

                ps.setString(1, usn);
                ps.setString(2, pass);

                ResultSet hasil = ps.executeQuery();
                if (hasil.next()) {
                    JOptionPane.showMessageDialog(this, "Login berhasil!");
                    Session.setUsername(hasil.getString("username"));
                    Session.setId(hasil.getString("id_user"));
                    if (hasil.getInt("level") == 1) {
                        Session.setRole("Admin");
                    } else {
                        Session.setRole("Karyawan");
                    }
                    new Main().setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Username atau Password salah!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eye = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        button1 = new com.raven.util.Button();
        userInput = new com.raven.util.TextField();
        passInput = new com.raven.util.PasswordField();
        shutdownBtn = new com.raven.util.Button();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KitchenShell 2.0 [Login Required]");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/crossed-eye.png"))); // NOI18N
        eye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyeMouseClicked(evt);
            }
        });
        getContentPane().add(eye, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PASSWORD");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USERNAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, 20));

        button1.setBackground(new java.awt.Color(97, 131, 175));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("LOGIN");
        button1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 240, -1));

        userInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userInputKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                userInputKeyTyped(evt);
            }
        });
        getContentPane().add(userInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 240, -1));

        passInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passInputKeyPressed(evt);
            }
        });
        getContentPane().add(passInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 240, -1));

        shutdownBtn.setBackground(new java.awt.Color(200, 10, 10));
        shutdownBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/power.png"))); // NOI18N
        shutdownBtn.setAlignmentY(0.0F);
        shutdownBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        shutdownBtn.setIconTextGap(0);
        shutdownBtn.setShadowColor(new java.awt.Color(120, 120, 120));
        shutdownBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shutdownBtnActionPerformed(evt);
            }
        });
        getContentPane().add(shutdownBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 40, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/Login/LOGIN (4).jpg"))); // NOI18N
        jLabel4.setText("jLabel1");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, -1));

        getAccessibleContext().setAccessibleDescription("Login Page for KitchenShell 2.0");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void shutdownBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shutdownBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_shutdownBtnActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        loginAction();
//        new Main().setVisible(true);
    }//GEN-LAST:event_button1ActionPerformed
    private String RFIDId = "";
    private long lastTime = 0;
    private final long RFID_THRESHOLD = 100;
    private void userInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userInputKeyTyped
        long currentTime = System.currentTimeMillis();
        char c = evt.getKeyChar();

        // Reset RFIDId kalau inputnya lambat
        if (lastTime != 0 && (currentTime - lastTime) > RFID_THRESHOLD) {
            RFIDId = "";
        }

        RFIDId += c;
        lastTime = currentTime;

        if (c == '\n' || c == '\r') {
            RFIDId = RFIDId.replace("\n", "");
            RFIDId = RFIDId.replace("\r", "");
            if (RFIDId.length() >= 9) {
                System.out.println("Scan RFID Terdeteksi: " + RFIDId);
                tampilRFID();
            } else {
                System.out.println("RFID tidak valid, panjang kurang dari 9 karakter.");
            }
            // Kosongkan RFIDId setelah pemrosesan
            RFIDId = "";
//            userInput.setText("");
        }
    }//GEN-LAST:event_userInputKeyTyped

    private void tampilRFID() {
        try {
            String query = "SELECT * FROM user WHERE uid = ? LIMIT 1";
            String rfid = RFIDId;
            try (PreparedStatement ps = con.prepareStatement(query)) {

                ps.setString(1, rfid);

                ResultSet hasil = ps.executeQuery();
                if (hasil.next()) {
                    userInput.setText(hasil.getString("username")); 
                    passInput.setText(hasil.getString("password"));
                    passInput.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(this, "RFID Tidak terdaftar!", "Error", JOptionPane.ERROR_MESSAGE);
                    userInput.setText("");
                    passInput.setText("");
                }
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private int indexEye = 1;
    private void eyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeMouseClicked

        if (indexEye == 0) {
            indexEye = 1;
            passInput.setEchoChar('*');
        } else {
            indexEye = 0;
            passInput.setEchoChar((char) 0);

        }
        ImageIcon icon = new ImageIcon(iconURL[indexEye]);
        eye.setIcon(icon);
    }//GEN-LAST:event_eyeMouseClicked

    private void passInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passInputKeyPressed
        if(evt.getKeyChar()== '\n'){
            loginAction();
        }
    }//GEN-LAST:event_passInputKeyPressed

    private void userInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userInputKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_userInputKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.util.Button button1;
    private javax.swing.JLabel eye;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private com.raven.util.PasswordField passInput;
    private com.raven.util.Button shutdownBtn;
    private com.raven.util.TextField userInput;
    // End of variables declaration//GEN-END:variables
}
