/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.popup;

import com.raven.event.DataChangeListener;
import config.DatabaseConfig;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicComboBoxUI;
import javax.swing.table.DefaultTableModel;
import raven.glasspanepopup.GlassPanePopup;

/**
 *
 * @author Fazaa
 */
public class PorsiPopup extends javax.swing.JPanel {

    /**
     * Creates new form PorsiPopup
     */
    Connection con = null;
    List<String> items;
    DefaultTableModel tableModel;
    private DataChangeListener dataChangeListener;

    public PorsiPopup() {
        initComponents();
        getCon();
        setModel();
        loadData();
        styling();
        setOpaque(false);
    }

    private void getCon() {
        try {
            con = DatabaseConfig.getConnection();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void setMenuListener(DataChangeListener listener) {
        this.dataChangeListener = listener;
    }

    private void setModel() {
        String[] judul = {"Kode Menu", "Nama Menu", "Jumlah"};
        tableModel = new DefaultTableModel(judul, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tbl_menu.setModel(tableModel);
    }

    private void loadData() {
        items = new ArrayList<String>();
        if (con != null) {
            try {
                String query = "SELECT * FROM menu";
                PreparedStatement ps = con.prepareStatement(query);
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    String kode_menu = rs.getString("kode_menu");
                    String nama_menu = rs.getString("nama_menu");
                    menuCombo.addItem(kode_menu + " | " + nama_menu);
                    items.add(kode_menu + " | " + nama_menu);
                }
                rs.close();
                ps.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }

    private void styling() {
        // Ganti font & warna
        // styling dasar
        menuCombo.setFont(new Font("Arial", Font.BOLD, 14));
        menuCombo.setForeground(new Color(50, 45, 20));
        menuCombo.setBackground(Color.WHITE);
        menuCombo.setOpaque(true);

// override hanya arrow button & background area
        menuCombo.setUI(new BasicComboBoxUI() {
            @Override
            protected JButton createArrowButton() {
                JButton arrow = super.createArrowButton();
                arrow.setBackground(Color.WHITE);
                arrow.setBorder(BorderFactory.createEmptyBorder());
                return arrow;
            }

            @Override
            public void paintCurrentValueBackground(Graphics g, Rectangle bounds, boolean hasFocus) {
                g.setColor(menuCombo.getBackground());
                g.fillRect(bounds.x, bounds.y, bounds.width, bounds.height);
            }
        });
        menuCombo.setLightWeightPopupEnabled(false);

        menuCombo.setEditable(true);

        JTextField editor = (JTextField) menuCombo.getEditor().getEditorComponent();

        editor.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent e) {
                String input = editor.getText();
                menuCombo.hidePopup();
                menuCombo.removeAllItems();

                for (String item : items) {
                    if (item.toLowerCase().contains(input.toLowerCase())) {
                        menuCombo.addItem(item);
                    }
                }

                editor.setText(input); // keep the text
                menuCombo.showPopup();
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new com.raven.swing.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBatal = new com.raven.util.Button();
        btnSelesai = new com.raven.util.Button();
        inputJumlah = new com.raven.util.TextField();
        jLabel4 = new javax.swing.JLabel();
        menuCombo = new javax.swing.JComboBox<>();
        button1 = new com.raven.util.Button();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_menu = new com.raven.swing.TableColumn();

        panelRound1.setBackground(new java.awt.Color(33, 53, 85));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TAMBAH PORSI");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 1, 1));
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama Menu");

        btnBatal.setBackground(new java.awt.Color(97, 131, 175));
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("Batal");
        btnBatal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnSelesai.setBackground(new java.awt.Color(97, 131, 175));
        btnSelesai.setForeground(new java.awt.Color(255, 255, 255));
        btnSelesai.setText("Selesai");
        btnSelesai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });

        inputJumlah.setText("0");
        inputJumlah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jumlah");

        menuCombo.setBorder(null);

        button1.setText("Tambahkan");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        jScrollPane2.setBorder(null);

        tbl_menu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KODE", "NAMA", "JUMLAH"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_menu.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbl_menu);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(jLabel4))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(menuCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(inputJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(349, 349, 349)
                        .addComponent(btnSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(0, 0, 0)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(menuCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inputJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        GlassPanePopup.closePopupAll();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        if (tableModel.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Tidak ada item dalam pesanan!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            con.setAutoCommit(false); // Mulai transaction

            // 3. Insert ke tabel detail_transaksi dan update stok
            for (int i = 0; i < tableModel.getRowCount(); i++) {
                String kodeMenu = (String) tableModel.getValueAt(i, 0);
                int jumlahPorsi = (Integer) tableModel.getValueAt(i, 2);

                String ket = "Porsi menu harian";
                String cekPorsi = "SELECT * FROM v_porsi_harian WHERE kode_menu = ?";
                PreparedStatement ps = con.prepareStatement(cekPorsi);
                ps.setString(1, kodeMenu);
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    ket = "Tambah porsi menu";
                }
                // Insert detail transaksi
                String queryPorsi = "INSERT INTO porsi_harian (kode_menu, jumlah, tanggal, keterangan) VALUES (?,  ?, NOW(), ?)";
                PreparedStatement psDetail = con.prepareStatement(queryPorsi);
                psDetail.setString(1, kodeMenu);
                psDetail.setInt(2, jumlahPorsi);
                psDetail.setString(3, ket);
                psDetail.executeUpdate();

            }

            con.commit(); // Commit transaction

            // Tampilkan pesan sukses dan reset form
            JOptionPane.showMessageDialog(this,
                    "berhasil Menambahkan Porsi!\n",
                    "Sukses", JOptionPane.INFORMATION_MESSAGE);
            if (dataChangeListener != null) {
                dataChangeListener.onDataChanged();
            }
            loadData(); // Refresh data menu

        } catch (SQLException e) {
            try {
                con.rollback();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error saat memproses transaksi: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                con.setAutoCommit(true);
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnSelesaiActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        String[] kodeMenu = menuCombo.getSelectedItem().toString().split("\\|");
        if (inputJumlah.equals("")) {
            return;
        }

        if (con != null) {
            try {
                String qCari = "SELECT * FROM menu WHERE kode_menu = ? LIMIT 1";
                PreparedStatement ps = con.prepareStatement(qCari);
                ps.setString(1, kodeMenu[0].trim());
                ResultSet rs = ps.executeQuery();
                if (rs != null) {
                    while (rs.next()) {
                        String namaMenu = rs.getString(3);
                        int jumlah = Integer.parseInt(inputJumlah.getText());
                        boolean cekKode = false;

                        //cek apakah ada kode menu yang sama
                        int row = tbl_menu.getRowCount();
                        for (int i = 0; i < row; i++) {
                            //jika ada akan menambahkan jumlah menu tersebut
                            int stokTabel = (int) tbl_menu.getValueAt(i, 2);
                            if (tbl_menu.getValueAt(i, 0).equals(kodeMenu[0].trim())) {
                                int jumlahBaru = Integer.parseInt(tbl_menu.getValueAt(i, 2).toString());
                                tbl_menu.setValueAt(jumlahBaru + jumlah, i, 2);
                                cekKode = true;
                                break;
                            }
                        }
                        if (!cekKode) {
                            tableModel.addRow(new Object[]{kodeMenu[0].trim(), namaMenu, jumlah});
                        }

                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Kode Menu Tidak Terdaftar!");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_button1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.util.Button btnBatal;
    private com.raven.util.Button btnSelesai;
    private com.raven.util.Button button1;
    private com.raven.util.TextField inputJumlah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> menuCombo;
    private com.raven.swing.PanelRound panelRound1;
    private com.raven.swing.TableColumn tbl_menu;
    // End of variables declaration//GEN-END:variables
}
